version: "3.8"
services:
  backend:
    build: .
    ports:
      - 3000:3000
    links:
      - db

  frontend:
    build: ./frontend
    tty: true
    ports:
      - 8080:3000
    links:
      - backend
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypass
